advisorresources
| where type == "microsoft.advisor/recommendations"
| where properties.category == "HighAvailability"
| where properties.extendedProperties.recommendationSubCategory == "ServiceUpgradeAndRetirement"
| extend retirementFeatureName = properties.extendedProperties.retirementFeatureName
| extend retirementDate = properties.extendedProperties.retirementDate
| extend resourceId = properties.resourceMetadata.resourceId
| extend shortDescription = properties.shortDescription.problem
// To exclude upgrade recommendations that are not linked to any retirement
| where retirementFeatureName != ''
| project retirementFeatureName, retirementDate, resourceId, shortDescription
